name: 테스트
description: 테스트 추가 / 실패 / 수정
title: "[Test 🧪] "
labels: ["Test 🧪"]
body:
  - type: dropdown
    id: test-type
    attributes:
      label: 종류
      description: 이슈 종류
      options:
        - github action / app
        - 코드 커버리지
        - 테스트 라이브러리
        - 테스트 수정
        - 테스트 추가
        - 테스트 실패
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 내용
